//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "Authors"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: Option<i32>,
    pub name: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Name,
    #[sea_orm(column_name = "createdAt")]
    CreatedAt,
    #[sea_orm(column_name = "updatedAt")]
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Option<i32>;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    AuthorAliases,
    AuthorsReferences,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def().null(),
            Self::Name => ColumnType::String(None).def().unique(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::AuthorAliases => Entity::has_many(super::author_aliases::Entity).into(),
            Self::AuthorsReferences => Entity::has_many(super::authors_references::Entity).into(),
        }
    }
}

impl Related<super::author_aliases::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuthorAliases.def()
    }
}

impl Related<super::authors_references::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuthorsReferences.def()
    }
}

impl Related<super::references::Entity> for Entity {
    fn to() -> RelationDef {
        super::authors_references::Relation::References.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::authors_references::Relation::Authors.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
