//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "AuthorsReferences"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub author_id: i32,
    pub reference_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    #[sea_orm(column_name = "authorId")]
    AuthorId,
    #[sea_orm(column_name = "referenceId")]
    ReferenceId,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    AuthorId,
    ReferenceId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = (i32, i32);
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Authors,
    References,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::AuthorId => ColumnType::Integer.def(),
            Self::ReferenceId => ColumnType::Integer.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Authors => Entity::belongs_to(super::authors::Entity)
                .from(Column::AuthorId)
                .to(super::authors::Column::Id)
                .into(),
            Self::References => Entity::belongs_to(super::references::Entity)
                .from(Column::ReferenceId)
                .to(super::references::Column::Id)
                .into(),
        }
    }
}

impl Related<super::authors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Authors.def()
    }
}

impl Related<super::references::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::References.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
