//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "Books"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub reference_id: i32,
    pub isbn: Option<String>,
    pub series_number: Option<String>,
    pub publisher_id: Option<i32>,
    pub series_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    #[sea_orm(column_name = "referenceId")]
    ReferenceId,
    Isbn,
    #[sea_orm(column_name = "seriesNumber")]
    SeriesNumber,
    #[sea_orm(column_name = "publisherId")]
    PublisherId,
    #[sea_orm(column_name = "seriesId")]
    SeriesId,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    ReferenceId,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Publishers,
    References,
    Series,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::ReferenceId => ColumnType::Integer.def().unique(),
            Self::Isbn => ColumnType::String(None).def().null(),
            Self::SeriesNumber => ColumnType::String(None).def().null(),
            Self::PublisherId => ColumnType::Integer.def().null(),
            Self::SeriesId => ColumnType::Integer.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Publishers => Entity::belongs_to(super::publishers::Entity)
                .from(Column::PublisherId)
                .to(super::publishers::Column::Id)
                .into(),
            Self::References => Entity::belongs_to(super::references::Entity)
                .from(Column::ReferenceId)
                .to(super::references::Column::Id)
                .into(),
            Self::Series => Entity::belongs_to(super::series::Entity)
                .from(Column::SeriesId)
                .to(super::series::Column::Id)
                .into(),
        }
    }
}

impl Related<super::publishers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Publishers.def()
    }
}

impl Related<super::references::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::References.def()
    }
}

impl Related<super::series::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Series.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
