//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod author_aliases;
pub mod authors;
pub mod authors_references;
pub mod books;
pub mod feature_tags;
pub mod feature_tags_magazine_features;
pub mod magazine_features;
pub mod magazine_issues;
pub mod magazines;
pub mod photo_collections;
pub mod publishers;
pub mod reference_types;
pub mod references;
pub mod series;
pub mod tags;
pub mod tags_references;
pub mod users;
