//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::author_aliases::Entity as AuthorAliases;
pub use super::authors::Entity as Authors;
pub use super::authors_references::Entity as AuthorsReferences;
pub use super::books::Entity as Books;
pub use super::feature_tags::Entity as FeatureTags;
pub use super::feature_tags_magazine_features::Entity as FeatureTagsMagazineFeatures;
pub use super::magazine_features::Entity as MagazineFeatures;
pub use super::magazine_issues::Entity as MagazineIssues;
pub use super::magazines::Entity as Magazines;
pub use super::photo_collections::Entity as PhotoCollections;
pub use super::publishers::Entity as Publishers;
pub use super::reference_types::Entity as ReferenceTypes;
pub use super::references::Entity as References;
pub use super::series::Entity as Series;
pub use super::tags::Entity as Tags;
pub use super::tags_references::Entity as TagsReferences;
pub use super::users::Entity as Users;
