//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize,
)]
#[sea_orm(table_name = "photo_collections")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub reference_id: i32,
    pub location: String,
    pub media: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::reference::Entity",
        from = "Column::ReferenceId",
        to = "super::reference::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Reference,
}

impl Related<super::reference::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Reference.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
