//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize,
)]
#[sea_orm(table_name = "authors")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::author_aliases::Entity")]
    AuthorAliases,
}

impl Related<super::author_aliases::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuthorAliases.def()
    }
}

impl Related<super::references::Entity> for Entity {
    fn to() -> RelationDef {
        super::authors_references::Relation::References.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::authors_references::Relation::Authors.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
