//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize,
)]
#[sea_orm(table_name = "feature_tags_magazine_features")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub feature_tag_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub magazine_feature_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::feature_tags::Entity",
        from = "Column::FeatureTagId",
        to = "super::feature_tags::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    FeatureTags,
    #[sea_orm(
        belongs_to = "super::magazine_features::Entity",
        from = "Column::MagazineFeatureId",
        to = "super::magazine_features::Column::ReferenceId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    MagazineFeatures,
}

impl Related<super::feature_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FeatureTags.def()
    }
}

impl Related<super::magazine_features::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MagazineFeatures.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
