//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize,
)]
#[sea_orm(table_name = "magazine_features")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub reference_id: i32,
    pub magazine_issue_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::magazine_issues::Entity",
        from = "Column::MagazineIssueId",
        to = "super::magazine_issues::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    MagazineIssues,
    #[sea_orm(
        belongs_to = "super::references::Entity",
        from = "Column::ReferenceId",
        to = "super::references::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    References,
}

impl Related<super::magazine_issues::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MagazineIssues.def()
    }
}

impl Related<super::references::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::References.def()
    }
}

impl Related<super::feature_tags::Entity> for Entity {
    fn to() -> RelationDef {
        super::feature_tags_magazine_features::Relation::FeatureTags.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::feature_tags_magazine_features::Relation::MagazineFeatures
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
