//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

pub use super::auth_scope::Entity as AuthScopes;
pub use super::author::Entity as Authors;
pub use super::author_alias::Entity as AuthorAliases;
pub use super::authors_references::Entity as AuthorsReferences;
pub use super::book::Entity as Books;
pub use super::feature_tag::Entity as FeatureTags;
pub use super::feature_tags_magazine_features::Entity as FeatureTagsMagazineFeatures;
pub use super::magazine::Entity as Magazines;
pub use super::magazine_feature::Entity as MagazineFeatures;
pub use super::magazine_issue::Entity as MagazineIssues;
pub use super::photo_collection::Entity as PhotoCollections;
pub use super::publisher::Entity as Publishers;
pub use super::reference::Entity as References;
pub use super::reference_type::Entity as ReferenceTypes;
pub use super::series::Entity as Series;
pub use super::tag::Entity as Tags;
pub use super::tags_references::Entity as TagsReferences;
pub use super::user::Entity as Users;
pub use super::users_auth_scopes::Entity as UsersAuthScopes;
