//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

pub mod prelude;

pub mod auth_scope;
pub mod author;
pub mod author_alias;
pub mod authors_references;
pub mod book;
pub mod feature_tag;
pub mod feature_tags_magazine_features;
pub mod magazine;
pub mod magazine_feature;
pub mod magazine_issue;
pub mod photo_collection;
pub mod publisher;
pub mod reference;
pub mod reference_type;
pub mod series;
pub mod tag;
pub mod tags_references;
pub mod user;
pub mod users_auth_scopes;
